name: Build & Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  send-tg-msg:
    name: Send TG message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Send Telegram message
        uses: proDreams/actions-telegram-notifier@main
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          thread_id: ${{ secrets.TELEGRAM_TOPIC_ID }}
          status: pending
          notify_fields: 'repo_with_tag,commit,workflow'
          title: 'Building docker images.'

  build-docker-images:
    name: Build ${{ matrix.image.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: 'Main Image'
            tag: 'remnawave/node:dev'
            dockerfile: 'Dockerfile'
            build_args: ''
          - name: 'SNI Image'
            tag: 'remnawave/node:sni-dev'
            dockerfile: 'Dockerfile'
            build_args: 'UPSTREAM_REPO=kastov'
          - name: 'Bun Image'
            tag: 'remnawave/node:bun-dev'
            dockerfile: 'Dockerfile.Bun'
            build_args: ''
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.image.name }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.image.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: ${{ matrix.image.build_args }}
          tags: ${{ matrix.image.tag }}

  send-finish-tg-msg:
    name: Send TG message
    needs: [build-docker-images]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Send Telegram message
        uses: proDreams/actions-telegram-notifier@main
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          thread_id: ${{ secrets.TELEGRAM_TOPIC_ID }}
          status: ${{ job.status }}
          notify_fields: 'repo_with_tag,commit,workflow'
          title: 'Build Dev finished.'

  notify-on-error:
    runs-on: ubuntu-latest
    needs: [build-docker-images]
    if: failure()
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Send error notification
        uses: proDreams/actions-telegram-notifier@main
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          thread_id: ${{ secrets.TELEGRAM_TOPIC_ID }}
          status: failure
          notify_fields: 'repo_with_tag,commit,workflow'
          title: 'Build Dev failed.'
